### ISSUE TITLE
state.shape[1] out of range on DDPG agent eval

### ISSUE THREAD

**Issue by ffrommel** [wwydmanski/RLinWiFi#11]
Hello.

My name is Fabián and I am doing my Master's thesis on topics of Wi-Fi network configuration optimization applying machine learning. First of all I would like to congratulate you for the work done and thank you for the code released publicly. I am testing it to better understand your work.

In particular, an error occurs when running the DDPG agent evaluation. It seems that the state is "tensor (5.)" and the state.shape is "torch.Size ([])", so doing state.shape[1] in forward function of model.py module gets tuple out of range. How can i fix this? Below I indicate the complete traceback.

Many thanks in advance.
Regards.

---

Traceback (most recent call last):
  File "scratch/linear-mesh/agent_training.py", line 84, in <module>
    parameters=hyperparams)
  File "/home/fabian/source/ns-3.29/scratch/linear-mesh/agents/teacher.py", line 155, in eval
    self.actions = agent.act(np.array(logger.stations, dtype=np.float32), add_noise)
  File "/home/fabian/source/ns-3.29/scratch/linear-mesh/agents/ddpg/agent.py", line 115, in act
    action_values = np.clip(self.actor_local(state).cpu().data.numpy(), 0, 6)
  File "/home/fabian/miniconda3/envs/rlinwifi-test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fabian/source/ns-3.29/scratch/linear-mesh/agents/ddpg/model.py", line 69, in forward
    h0 = torch.randn(1, state.shape[1], self.fc_units).to(device)
IndexError: tuple index out of range

**Comment by ffrommel** [comment]
Hello.

Finally I think I found the problem. In the eval() function of the teacher.py module, the number of stations is used as state, while in train() function an array of observations is used, hence the problem with dimensions. I changed the state of eval() to be the same as in train() and it worked correctly.

Regards.

**Comment by wwydmanski** [comment]
Hi! 
Thanks for reaching out. It appears that I forgot to clean up the code after benchmarking optimal values - the line 155 was there because the lookup agent was hardcoded basing on the number of stations.
If you want to do a pull request with your fix I will be happy to merge it.

Best,
Witek

**Comment by ffrommel** [comment]
Hello Witek.

Thank you for the explanation. I created the pull request that fixes this minor bug.

Regards,
Fabian.
