### ISSUE TITLE
Query about the reward function

### ISSUE THREAD

**Issue by ffrommel** [wwydmanski/RLinWiFi#14]
Hello,

I have been doing some tests with this code and analyzing it in detail and it is not clear to me how the reward function was found, which, as the paper indicates, is the normalized thrughput. The formula is:

`float res = g_rxPktNum - last_packets;`
`float reward = res * (1500 - 20 - 8 - 8) * 8.0 / 1024 / 1024 / (5 * 150 * envStepTime) * 10;`

I understand that the throughput in Mbps is: **res * (1500 - 20 - 8 - 8) * 8.0 / 1024/1024 / envStepTime**, however, I cannot understand how the normalization factor was found: **10 / 5 * 150**.

Thank you very much in advance.
Regards,

Fabián.

**Comment by wwydmanski** [comment]
Hi,
AFAIR a few of those coefficients were found experimentally basing on
initial results.
The reasoning for their existence was that some DRL papers suggested having
the reward limited between 0 and 1.

Best,
Witek
