### ISSUE TITLE
some problem in tf_agent_training.py

### ISSUE THREAD

**Issue by zlh004** [wwydmanski/RLinWiFi#7]
when i run the 'tf_agent_training.py', it will show 'Please start proper ns-3 simulation script using ./waf --run "..." '
what should i do? thanks a lot

**Comment by wwydmanski** [comment]
This is a debug message displayed by ns3gym internals. It doesn't have any impact on the simulation itself, I have now added this information to the readme. 
Does the script continue after this info or is it stuck?

**Comment by wwydmanski** [comment]
I'm closing the issue for now due to inactivity, but feel free to reopen it if the problem still arises
